# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 17.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Check Prettier
        run: npm run prettier-check

      - name: Check TypeScript
        run: npm run tsc

      - name: Check Linting
        run: npm run lint

      - name: Run Tests
        run: npm run test:coverage

      - name: Build project
        run: npm run build

      - name: Codecov
        uses: codecov/codecov-action@v2

  cypress-firefox:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.5.0-chrome97-ff96
      options: --user 1001 # Firefox needs a non-root user due to security restrictions
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress Firefox tests
        uses: cypress-io/github-action@v2
        with:
          browser: firefox
          start: npm run start-node-16
          wait-on: http://localhost:3000
          wait-on-timeout: 300

  cypress-chrome:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.5.0-chrome97-ff96
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress Chrome tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm run start-node-16
          wait-on: http://localhost:3000
          wait-on-timeout: 300
